"""Rearrange existing V8 results into PLA figures without new parameter scans.

Usage: python repro/make_pla_figures.py [--output-dir path]
Existing plots are regenerated by make_figures.py, which also repeats the two
already reported profile solves. All quantitative datasets are read-only.
"""
from pathlib import Path
import argparse
import runpy
import shutil
import sys
import json
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

BASE=Path(__file__).resolve().parents[1]
parser=argparse.ArgumentParser()
parser.add_argument('--output-dir',type=Path,default=BASE/'pla_figures')
args=parser.parse_args()
OUT=args.output_dir.resolve(); OUT.mkdir(parents=True,exist_ok=True)
(BASE/'source'/'figures').mkdir(parents=True,exist_ok=True)
sys.path.insert(0,str(BASE/'repro'))
runpy.run_path(str(BASE/'repro'/'make_figures.py'),run_name='__main__')
from model import fold_theory,melnikov

D=BASE/'data'; legacy=BASE/'source'/'figures'
mapping={'fig5':'pla_fig2','fig6':'pla_fig3','fig1':'pla_sfig7','fig2':'pla_sfig8'}
mapping.update({f'figS{i}':f'figS{i}' for i in range(1,6)})
for old,new in mapping.items(): shutil.copy2(legacy/f'{old}.pdf',OUT/f'{new}.pdf')

plt.rcParams.update({'font.family':'DejaVu Sans','font.size':8,'axes.labelsize':9,
 'axes.titlesize':9,'legend.fontsize':7,'xtick.labelsize':8,'ytick.labelsize':8,
 'lines.linewidth':1.3,'pdf.fonttype':42,'ps.fonttype':42,
 'axes.spines.top':False,'axes.spines.right':False,'savefig.pad_inches':.04})
colors=['#286CA6','#D16A28','#259273','#8B5BA5','#A24459']
folds=pd.read_csv(D/'folds_80.csv')
vals=json.loads((D/'representative_values.json').read_text())
def panels(axes):
 for letter,ax in zip('abcdefghijkl',np.asarray(axes).ravel()):
  ax.text(0,1.04,'('+letter+')',transform=ax.transAxes,weight='bold',va='bottom')
  ax.grid(alpha=.13,lw=.5)
def save(fig,name):
 fig.savefig(OUT/f'{name}.pdf',bbox_inches='tight')
 plt.close(fig)

fig,ax=plt.subplots(2,2,figsize=(7,4.45))
fig.subplots_adjust(left=.10,right=.99,bottom=.11,top=.84,hspace=.53,wspace=.30)
panels(ax)
for i,beta in enumerate(sorted(folds.beta.unique())):
 for sigma,marker,style in [(1,'o','-'),(-1,'s','--')]:
  r=folds[(folds.beta==beta)&(folds.sigma==sigma)].sort_values('m')
  kw=dict(color=colors[i],marker=marker,ms=3,ls=style)
  ax[0,0].semilogy(r.m,r.epsilon,**kw)
  ax[0,1].plot(r.m.values[:-1],-np.diff(np.log(r.epsilon))/beta,**kw)
  ax[1,0].plot(beta*r.m,r.rho,**kw)
  ax[1,1].semilogy(beta*r.m,r.relative_error,**kw)
ax[0,0].set(xlabel='Integer separation $m$',ylabel=r'$\varepsilon_{\rm fold}$')
ax[0,1].axhline(1,c='black',lw=.7)
ax[0,1].set(xlabel='$m$ (pair $m,m+1$)',ylabel=r'$\kappa_{\rm fold}/\beta$')
ax[1,0].axhline(1,c='black',lw=.7)
ax[1,0].set(xlabel=r'$\beta m$',ylabel=r'$\rho=\varepsilon_{\rm fold}/(C_\sigma e^{-\beta m})$')
ax[1,1].set(xlabel=r'$\beta m$',ylabel=r'$|\rho-1|$')
handles=[Line2D([0],[0],color=c,label=rf'$\beta={b:g}$') for c,b in zip(colors,sorted(folds.beta.unique()))]
fig.legend(handles=handles,loc='upper center',bbox_to_anchor=(.54,1.0),ncol=5,frameon=False)
phase=[Line2D([0],[0],color='.3',marker='o',ms=3,label='Equal phase'),Line2D([0],[0],color='.3',marker='s',ms=3,ls='--',label='Opposite phase')]
fig.legend(handles=phase,loc='upper center',bbox_to_anchor=(.54,.945),ncol=2,frameon=False)
save(fig,'pla_fig1')

fig,ax=plt.subplots(1,2,figsize=(7,2.55),layout='constrained');panels(ax)
for j in range(3):
 z=np.load(D/f'dns_stable{j}_a1e-06_tol1e-10.npz');t=z['t'];freq=z['lambda_bdg'].imag;c=z['c']/z['c'][0];select=t<400
 ax[0].plot(t[select],c.real[select]+2.3*j,color=colors[j])
 ax[0].plot(t[select][::20],np.cos(freq*t[select][::20])+2.3*j,'o',ms=2,color='black')
ax[0].set(xlabel='$t$',ylabel='Normalized modal signal + offset')
ax[0].set_yticks([0,2.3,4.6],['Ex.','PN','Str.'])
z=np.load(D/'dns_real_a1e-06_tol1e-10.npz');t=z['t'];y=np.log(abs(z['c']/z['c'][0]))
ax[1].plot(t,y,color=colors[0],label='Time integration')
ax[1].plot(t[::120],z['lambda_bdg'].real*t[::120],'o',ms=2,c='black',label='Spectral prediction')
ax[1].set(xlabel='$t$',ylabel=r'$\ln|c(t)/c(0)|$');ax[1].legend(frameon=False)
save(fig,'pla_fig4')

fig,ax=plt.subplots(figsize=(6.6,2.5),layout='constrained')
for tag,col,label in [('matched',colors[0],'Invariant matched'),('residence',colors[1],r'$\alpha=0.0062$'),('fast',colors[2],r'$\alpha=0.0100$')]:
 z=np.load(D/f'collision_{tag}.npz');ax.plot(z['t'],z['Rmol'],color=col,label=label)
ax.axhspan(vals['Rmol']-2,vals['Rmol']+2,color='gray',alpha=.2)
ax.set(xlabel='$t$',ylabel=r'$R_{\rm mol}(t)$',ylim=(5,105));ax.legend(frameon=False,loc='upper left');ax.grid(alpha=.13,lw=.5)
save(fig,'pla_sfig6')

fig,ax=plt.subplots(1,2,figsize=(7,2.6),layout='constrained');panels(ax)
for sigma,col in [(1,colors[0]),(-1,colors[1])]:
 xf,C,K=fold_theory(1,sigma)
 xx=np.linspace(-.49,-.01,400) if sigma==1 else np.linspace(.01,.49,400)
 cc=np.array([-sigma*K*np.exp(-2*z)/melnikov(-z,1) for z in xx])
 ax[0].plot(xx,cc/C,color=col,label=r'$\sigma=+1$' if sigma==1 else r'$\sigma=-1$')
 ax[0].plot(xf,1,'o',color=col,ms=4)
ax[0].set(xlabel='$x$',ylabel=r'$C_\sigma(x)/C_\sigma(x_*)$',ylim=(.9,3.5));ax[0].legend(frameon=False)
th=pd.read_csv(D/'fredholm_prefactors.csv')
for sig,marker,label in [(1,'o',r'$C_0$'),(-1,'s',r'$C_\pi$')]:
 r=th[th.sigma==sig];ax[1].semilogy(r.beta,r.C,marker+'-',ms=4,label=label)
ax[1].set(xlabel=r'$\beta$',ylabel='Fold prefactor');ax[1].legend(frameon=False)
save(fig,'pla_sfig9')
print(f'PLA vector figures written to {OUT}')
